name: Nightly Development Build

on:
    schedule:
      - cron: '0 2 * * *'
    workflow_dispatch:
    
jobs:
    testing:
      uses: mklomp/mirte-sd-image-tools/.github/workflows/buildFork.yaml@33b261ed1cb36171e392a28a957d05464d3636e9
