name: Nightly Development Build

on:
    schedule:
      - cron: '0 2 * * *'
    workflow_dispatch:
    
jobs:
    testing:
      uses: mklomp/mirte-sd-image-tools/.github/workflows/buildFork.yaml@20628da02027f3d0d1f77700c43619ab82e5b0f3
