name: Publish other repos

on:
    release:
        types: [published]
permissions:
    contents: write

jobs:
    upload-repos:
        # container:
        #   image: ubuntu:22.04
        #   options: --privileged
        runs-on: ubuntu-latest
        strategy:
            matrix:
                repo:
                    [
                        "mirte-install-scripts",
                        "mirte-ros-packages",
                        "mirte-python",
                        "telemetrix4rpipico",
                        "mirte-web-interface",
                        "mirte-frame",
                        "tmx-pico-aio",
                        "telemetrix-aio",
                        "telemetrix4arduino",
                        "mirte-pcb",
                        "mirte-documentation",
                    ]
            fail-fast: false
        steps:
            - run: |
                  git clone https://github.com/mirte-robot/${{ matrix.repo }}.git
                  zip -r ${{ matrix.repo }}.zip ${{ matrix.repo }}
            - name: Push to release
              uses: softprops/action-gh-release@v2
              if: startsWith(github.ref, 'refs/tags/')
              with:
                  files: ${{ matrix.repo }}.zip
