name: Rerunner

on:
  workflow_dispatch:
    inputs:
      original_run_id:
        description: "Run ID to rerun"
        type: number
        required: true

jobs:
  rerun:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: develop
      - name: Echo inputs
        run: |
          echo "Original run ID: ${{ github.event.inputs.original_run_id }}"
      - name: Rerun the original workflow
        run: |
          gh run rerun ${{ github.event.inputs.original_run_id }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
